export enum ErrorEnums {
  ERROR_NO_CHANGELOG_FILE = 'ERROR_NO_CHANGELOG_FILE',
  ERROR_NO_CHANGELOG_UPDATES = 'ERROR_NO_CHANGELOG_UPDATES',
  ERROR_CHANGELOG_MISSING_CHANGES = 'ERROR_CHANGELOG_MISSING_CHANGES',
  ERROR_BRANCH_WRONG_NAMING_PATTERN = 'ERROR_BRANCH_WRONG_NAMING_PATTERN',
  ERROR_BRANCH_IS_MAIN = 'ERROR_BRANCH_IS_MAIN',
  ERROR_MUST_COMMIT_NEW_CHANGES = 'ERROR_MUST_COMMIT_NEW_CHANGES',
}
